export default {
  HOME: 'home',
  BACK_BUTTON: 'arrow-back',
  BASKETBALL: 'sports-basketball',
  SCHOOL: 'school',
  SETTINGS: 'settings',
  MOOD_BAD: 'mood-bad',
  MOOD: 'mood',
  ICECREAM: 'icecream',
  GET_APP: 'get-app',
  FEEDBACK: 'feedback',
  EDIT: 'edit',
  CANCEL: 'cancel',
  STARS: 'stars',
  RECOMMEND: 'recommend',
  READ_MORE: 'read-more',
  BEENHERE: 'beenhere',
  GAME_CONTROLLER: 'game-controller',
  ARROW_LEFT: 'arrow-left',
  ARROW_RIGHT: 'arrow-right',
  LOCK: 'lock',
};
