export default {
  sqli: require('../assets/images/sql-injection.png'),
  hacker_cracked: require('../assets/images/hacker_cracked.png'),
  lock: require('../assets/images/lock.png'),
  sweets: require('../assets/images/sweets.png'),
  detective: require('../assets/images/detective.png'),
  snmp: require('../assets/images/archive_snmp.png'),
  dns: require('../assets/images/dns.png'),
  ftp: require('../assets/images/ftp.png'),
  network: require('../assets/images/network.png'),
  smb: require('../assets/images/storage_smb.png'),
  website: require('../assets/images/website.png'),
  path: require('../assets/images/path.png'),
  privesc: require('../assets/images/privilege-escalation.png'),
  xss: require('../assets/images/xss.png'),
  ssti: require('../assets/images/ssti.png'),
  xxe: require('../assets/images/xml.png'),
  rfi: require('../assets/images/rfi.png'),
  boy: require('../assets/images/boy.png'),
  april: require('../assets/images/mooney/april.png'),
  cross: require('../assets/images/mooney/cross.png'),
  israel: require('../assets/images/mooney/israel.png'),
  location: require('../assets/images/mooney/location.png'),
};
